# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$build = <<SCRIPT
echo "deb http://ppa.launchpad.net/mapnik/boost/ubuntu precise main" >> /etc/apt/sources.list.d/hhvm.list
echo "deb-src http://ppa.launchpad.net/mapnik/boost/ubuntu precise main" >> /etc/apt/sources.list.d/hhvm.list
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5D50B6BA
apt-get install -y wget
wget -O - http://dl.hhvm.com/conf/hhvm.gpg.key | apt-key add -
echo "deb http://dl.hhvm.com/ubuntu precise main" >> /etc/apt/sources.list.d/hhvm.list

apt-get update
apt-get install -y hhvm-nightly

SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.network :forwarded_port, guest: 80, host: 4280

  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider :virtualbox do |vb|
    vb.name = "HHVM"
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--cpus", "4"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--nestedpaging", "on"]
  end
  config.vm.provision :shell, inline: $build
end
